server:
  port: 8080
  mode: debug  # debug/release

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: cryptosignal
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

